#!/bin/bash

# LieferMax WordPress - Interaktive Setup-Anleitung
# Führt Sie durch alle Schritte nach der WordPress-Installation

set -e

# Farben für Output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     LieferMax WordPress - Setup Assistent                 ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Step 1: Check
echo -e "${GREEN}✓ Step 1: WordPress installiert${NC}"
echo ""

# Step 2: Theme aktivieren
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 2: Theme aktivieren${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Bitte folgende Schritte im Browser durchführen:"
echo ""
echo "1. WordPress Admin öffnen:"
echo -e "   ${GREEN}http://localhost:8080/wp-admin${NC}"
echo ""
echo "2. Einloggen mit Ihren Zugangsdaten"
echo ""
echo "3. Theme aktivieren:"
echo "   Dashboard → Design → Themes"
echo "   → 'LieferMax Redesign' suchen"
echo "   → 'Aktivieren' klicken"
echo ""
read -p "Drücken Sie Enter wenn Theme aktiviert ist..."
echo -e "${GREEN}✓ Theme aktiviert${NC}"
echo ""

# Step 3: XML Import
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 3: WordPress XML importieren${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. WordPress Importer installieren:"
echo "   Dashboard → Werkzeuge → Daten importieren"
echo "   → 'WordPress' → 'Jetzt installieren'"
echo "   → 'Importer ausführen'"
echo ""
echo "2. XML-Datei hochladen:"
echo "   → 'Datei auswählen'"
echo -e "   → Datei: ${GREEN}client_input/liefermaxgfghlieferscheinfahrerverkaufssystem.WordPress.2026-02-05.xml${NC}"
echo "   → 'Datei hochladen und importieren'"
echo ""
echo "3. Import-Optionen:"
echo "   → Autor zuweisen: 'admin'"
echo "   → ✓ 'Dateianhänge herunterladen und importieren'"
echo "   → 'Absenden'"
echo ""
echo -e "${YELLOW}⏳ Import kann 1-2 Minuten dauern...${NC}"
echo ""
read -p "Drücken Sie Enter wenn Import abgeschlossen ist..."
echo -e "${GREEN}✓ XML importiert (17 Seiten)${NC}"
echo ""

# Step 4: Permalinks
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 4: Permalinks konfigurieren${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Dashboard → Einstellungen → Permalinks"
echo "→ 'Beitragsname' auswählen"
echo "→ 'Änderungen speichern'"
echo ""
read -p "Drücken Sie Enter wenn Permalinks gesetzt sind..."
echo -e "${GREEN}✓ Permalinks konfiguriert${NC}"
echo ""

# Step 5: Menüs
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 5: Menüs erstellen${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. Hauptmenü erstellen:"
echo "   Dashboard → Design → Menüs"
echo "   → 'Neues Menü erstellen'"
echo "   → Name: 'Hauptmenü'"
echo ""
echo "2. Seiten hinzufügen:"
echo "   → LieferMax"
echo "   → LieferMax-CHECK"
echo "   → LieferMax-MAP"
echo "   → ShopWare & WooCommerce"
echo "   → Bestell App"
echo "   → Kontakt"
echo ""
echo "3. Position festlegen:"
echo "   → 'Primary Menu' aktivieren"
echo "   → 'Menü speichern'"
echo ""
read -p "Drücken Sie Enter wenn Menü erstellt ist..."
echo -e "${GREEN}✓ Menüs konfiguriert${NC}"
echo ""

# Step 6: Logo
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 6: Logo hochladen${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Dashboard → Design → Customizer"
echo "→ 'Website-Identität'"
echo "→ 'Logo auswählen'"
echo "→ 'Datei hochladen'"
echo -e "→ Datei: ${GREEN}wordpress-theme/assets/images/logo.png${NC}"
echo "→ Größe anpassen (ca. 50px Höhe)"
echo "→ 'Veröffentlichen'"
echo ""
read -p "Drücken Sie Enter wenn Logo hochgeladen ist..."
echo -e "${GREEN}✓ Logo konfiguriert${NC}"
echo ""

# Step 7: ngrok
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 7: ngrok für Demo starten${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if ngrok is installed
if command -v ngrok &> /dev/null; then
    echo -e "${GREEN}✓ ngrok ist installiert${NC}"
    echo ""
    echo "Starte ngrok in neuem Terminal-Fenster..."
    echo ""
    echo -e "${YELLOW}Führen Sie in einem NEUEN Terminal aus:${NC}"
    echo -e "${GREEN}ngrok http 8080${NC}"
    echo ""
    echo "Notieren Sie die Forwarding-URL:"
    echo "z.B. https://abc123.ngrok.io"
    echo ""
    read -p "Drücken Sie Enter wenn ngrok läuft..."
    echo ""
    echo "WordPress URLs anpassen:"
    echo "Dashboard → Einstellungen → Allgemein"
    echo "→ WordPress-Adresse (URL): [Ihre ngrok-URL]"
    echo "→ Website-Adresse (URL): [Ihre ngrok-URL]"
    echo "→ 'Änderungen speichern'"
    echo ""
    read -p "Drücken Sie Enter wenn URLs angepasst sind..."
    echo -e "${GREEN}✓ ngrok konfiguriert${NC}"
else
    echo -e "${RED}✗ ngrok ist nicht installiert${NC}"
    echo ""
    echo "Installieren Sie ngrok:"
    echo "1. Download: https://ngrok.com/download"
    echo "2. Oder via snap: sudo snap install ngrok"
    echo ""
    echo "Dann in neuem Terminal:"
    echo -e "${GREEN}ngrok http 8080${NC}"
    echo ""
    read -p "Drücken Sie Enter um fortzufahren..."
fi
echo ""

# Step 8: Tests
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 8: Tests durchführen${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Öffnen Sie die Test-Suite:"
echo -e "${GREEN}cat tests/test-suite.md${NC}"
echo ""
echo "Testen Sie:"
echo "1. Content vollständig (alle 17 Seiten)"
echo "2. Design schlicht mit Rot-Akzent"
echo "3. Logo auf allen Seiten"
echo "4. Responsive (Mobile, Tablet, Desktop)"
echo "5. Browser-kompatibel"
echo "6. Performance (Lighthouse)"
echo ""
read -p "Drücken Sie Enter wenn Tests abgeschlossen sind..."
echo -e "${GREEN}✓ Tests durchgeführt${NC}"
echo ""

# Fertig
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    ✓ SETUP ABGESCHLOSSEN                  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Ihre WordPress-Site ist bereit!${NC}"
echo ""
echo "Demo-Link für Kunde:"
echo -e "${GREEN}[Ihre ngrok-URL]${NC}"
echo ""
echo "Nächste Schritte:"
echo "1. Demo-Link an Kunde senden"
echo "2. Feedback sammeln"
echo "3. Anpassungen machen"
echo "4. Zu Ionos/Kunden-Server deployen"
echo ""
echo -e "${YELLOW}Viel Erfolg! 🚀${NC}"
